@startuml
'https://plantuml.com/activity-diagram-beta
skinparam defaultFontName "JetBrains Mono"
skinparam defaultFontSize 12
skinparam defaultFontColor #222222
skinparam titleFontSize 20
skinparam DefaultTextAlignment center
title Activity Diagram - (USD10: Mengubah Password)

|<b><font size=16>Pengguna</font></b>|
start
:Klik profile user;
|<b><font size=16>Sistem</font></b>|
:Tampilkan menu user;
|<b><font size=16>Pengguna</font></b>|
:Klik "Change password" pada menu user;
|<b><font size=16>Sistem</font></b>|
:Menampilkan form untuk mengganti password;
|<b><font size=16>Pengguna</font></b>|
:Masukan password lama dan password baru
kemudian Klik "save change";
|<b><font size=16>Sistem</font></b>|
if (apakah password valid?) then (Ya)
    :Simpan update ke dalam database;
    else (Tidak)
    :Menampilkan error ke user;
  endif
stop

@enduml
