@startumluy
skinparam defaultFontName "JetBrains Mono"
skinparam defaultFontSize 14
skinparam defaultFontColor #222222
skinparam titleFontSize 20
skinparam Linetype polyline
left to right direction
title Use Case Diagram - Wallet Document System

actor Pengguna as p

rectangle "Sistem Aplikasi Dompet Dokumen" {
  (F001: Register) as F001
  (F002: Login) as F002
  (F003: Logout) as F003
  (F004: Mengelola Dokumen) as F004
  (F005: Download Dokumen) as F005
  (F006: Membuka Dokumen) as F006
  (F007: Mengelola Dokumen Share) as F007
  (F008: Mengelola Dokumen Dibagikan Kepada Saya) as F008
  (F009: Mengelola Contact) as F009
  (F010: Mengelola Dokumen Trash) as F010
  (F011: Menukar Wallet) as F011
  (F012: Mengubah Password) as F012

}

' ==================== RELATIONSHIP ====================
p -- F001
p -- F002
' ' USD03 ..> USD06 : <<extend>>
' ' USD03 ..> USD07 : <<extend>>
p -- F004
F004 ..> F006 : <<extend>>
F004 ..> F005 : <<extend>>
F004 ..> F007 : <<extend>>
F009 ..> F007 : <<extend>>
' p -- F007
p -- F009
p -- F008
p -- F010
p -- F011
p -- F012
p -- F003

@enduml