@startuml
skinparam defaultFontName "JetBrains Mono"
skinparam defaultFontSize 14
skinparam defaultFontColor #222222
skinparam titleFontSize 20
title Sequence Diagram - (F006: Membuka Document)

actor Pengguna as User
boundary "Open" as View
control "Document" as System
entity "User" as DB
entity "Document" as DB2
database "Storage" as Storage

activate User
User -> View: Masukan password verifikasi
activate View
View -> System: Kirim password
deactivate View

    activate System
    System -> DB: GetVerifyPassword()
alt Verify gagal
    activate DB
    DB -> System: Kembalikan respon gagal verify
    System -> View: Kembalikan gagal verify
    deactivate System
    activate View
    View -> User: Tampilkan "password incorrect"
    deactivate View
else Verify berhasil
    DB -> System: Kembalikan respon berhasil verify
    deactivate DB
    activate System
    System -> View: Kembalikan berhasil verify
    deactivate System
    activate View
end
View -> System: Kirim document id
deactivate View
activate System
activate DB2
System -> DB2: GetDocumentById()
DB2 -> System: Kembalikan data document
System -> DB2: GetPathDocument()
DB2 -> Storage: Download chiphertext file 
deactivate DB2
activate Storage
Storage -> System: Kembalikan chiphertext file 
deactivate Storage
System -> View: Decrypt chiphertext 
deactivate System
activate View
View -> User: Tampilkan isi document
deactivate View
deactivate User
@enduml