@startuml
skinparam defaultFontName "JetBrains Mono"
skinparam defaultFontSize 14
skinparam defaultFontColor #222222
skinparam titleFontSize 20
title Sequence Diagram - (USD10: Mengubah Password)

actor Pengguna as User
boundary "Change Password" as View
control "Auth" as System
entity "User" as DB

activate User
User -> View: Masukan password lama dan baru
activate View
View -> System: Kirim password lama
deactivate View

    activate System
    System -> DB: GetVerifyPassword()
alt Verify gagal
    deactivate System
    activate DB
    DB -> System: Kembalikan respon gagal verify
    activate System
    System -> View: Kembalikan gagal verify
    deactivate System
    activate View
    View -> User: Tampilkan "password incorrect"
    deactivate View
else Verify berhasil
    DB -> System: Kembalikan respon berhasil verify
    deactivate DB
    activate System
    System -> View: Kembalikan berhasil verify
    deactivate System
    activate View
end
    View -> System: Kirim password baru
    ' deactivate View
    activate System
    System -> DB: UpdatePasswordByuserId()
    deactivate System
    activate DB
    DB -> System: Kembalikan respon success update
    deactivate DB
    activate System
    System -> View: Kembalikan success update
    deactivate System
    ' activate View
    View -> User: Tampilkan allert success
    deactivate View
deactivate User
@enduml